import "dotenv/config";
import { drizzle } from "drizzle-orm/node-postgres";
import type { InferInsertModel } from "drizzle-orm";
import { ingredients } from "./schema";

export const db = drizzle({
  connection: {
    connectionString: process.env.DATABASE_URL ?? "",
  },
});

const ingredientData: Omit<InferInsertModel<typeof ingredients>, "id">[] = [
  // Proteins
  {
    name: "Chicken Breast",
    category: "proteins",
    texture: "firm_solid",
    calories: 120,
    protein: 25,
    carbs: 0,
    fat: 2.5,
    fiber: 0,
    water_percentage: 75,
    energy_density: 120,
    is_vegetarian: false,
    is_vegan: false,
    slider_min: 50,
    slider_max: 300,
  },
  {
    name: "Beef, Lean Ground",
    category: "proteins",
    texture: "firm_solid",
    calories: 250,
    protein: 26,
    carbs: 0,
    fat: 15,
    fiber: 0,
    water_percentage: 60,
    energy_density: 250,
    is_vegetarian: false,
    is_vegan: false,
    slider_min: 50,
    slider_max: 300,
  },
  {
    name: "Eggs, Whole",
    category: "proteins",
    texture: "soft_solid",
    calories: 155,
    protein: 13,
    carbs: 1.1,
    fat: 11,
    fiber: 0,
    water_percentage: 76,
    energy_density: 155,
    is_vegetarian: true,
    is_vegan: false,
    slider_min: 50,
    slider_max: 200,
  },
  {
    name: "Tofu, Firm",
    category: "proteins",
    texture: "soft_solid",
    calories: 144,
    protein: 15,
    carbs: 3.5,
    fat: 8.7,
    fiber: 2.8,
    water_percentage: 70,
    energy_density: 144,
    is_vegetarian: true,
    is_vegan: true,
    slider_min: 50,
    slider_max: 250,
  },
  {
    name: "Salmon, Atlantic",
    category: "proteins",
    texture: "firm_solid",
    calories: 208,
    protein: 20,
    carbs: 0,
    fat: 13,
    fiber: 0,
    water_percentage: 65,
    energy_density: 208,
    is_vegetarian: false,
    is_vegan: false,
    slider_min: 50,
    slider_max: 250,
  },

  // Dairy
  {
    name: "Greek Yogurt",
    category: "dairy",
    texture: "semi_liquid",
    calories: 100,
    protein: 10,
    carbs: 6,
    fat: 0,
    fiber: 0,
    water_percentage: 85,
    energy_density: 100,
    is_vegetarian: true,
    is_vegan: false,
    slider_min: 50,
    slider_max: 300,
  },
  {
    name: "Milk, Whole",
    category: "dairy",
    texture: "liquid",
    calories: 61,
    protein: 3.2,
    carbs: 4.8,
    fat: 3.3,
    fiber: 0,
    water_percentage: 87,
    energy_density: 61,
    is_vegetarian: true,
    is_vegan: false,
    slider_min: 100,
    slider_max: 500,
  },
  {
    name: "Cheddar Cheese",
    category: "dairy",
    texture: "firm_solid",
    calories: 402,
    protein: 25,
    carbs: 1.3,
    fat: 33,
    fiber: 0,
    water_percentage: 37,
    energy_density: 402,
    is_vegetarian: true,
    is_vegan: false,
    slider_min: 20,
    slider_max: 150,
  },

  // Grains/Carbs
  {
    name: "White Rice, Cooked",
    category: "grains",
    texture: "soft_solid",
    calories: 130,
    protein: 2.7,
    carbs: 28,
    fat: 0.3,
    fiber: 0.4,
    water_percentage: 69,
    energy_density: 130,
    is_vegetarian: true,
    is_vegan: true,
    slider_min: 50,
    slider_max: 300,
  },
  {
    name: "Brown Rice, Cooked",
    category: "grains",
    texture: "soft_solid",
    calories: 112,
    protein: 2.6,
    carbs: 23,
    fat: 0.9,
    fiber: 1.8,
    water_percentage: 73,
    energy_density: 112,
    is_vegetarian: true,
    is_vegan: true,
    slider_min: 50,
    slider_max: 300,
  },
  {
    name: "Pasta, Cooked",
    category: "grains",
    texture: "soft_solid",
    calories: 131,
    protein: 5,
    carbs: 25,
    fat: 1.1,
    fiber: 1.8,
    water_percentage: 62,
    energy_density: 131,
    is_vegetarian: true,
    is_vegan: true,
    slider_min: 50,
    slider_max: 300,
  },
  {
    name: "Oats, Rolled",
    category: "grains",
    texture: "soft_solid",
    calories: 379,
    protein: 13.2,
    carbs: 67.7,
    fat: 6.5,
    fiber: 10.1,
    water_percentage: 8,
    energy_density: 379,
    is_vegetarian: true,
    is_vegan: true,
    slider_min: 30,
    slider_max: 150,
  },
  {
    name: "Sweet Potato",
    category: "grains",
    texture: "firm_solid",
    calories: 86,
    protein: 1.6,
    carbs: 20,
    fat: 0.1,
    fiber: 3,
    water_percentage: 77,
    energy_density: 86,
    is_vegetarian: true,
    is_vegan: true,
    slider_min: 100,
    slider_max: 300,
  },
  {
    name: "Quinoa, Cooked",
    category: "grains",
    texture: "soft_solid",
    calories: 120,
    protein: 4.4,
    carbs: 21,
    fat: 1.9,
    fiber: 2.8,
    water_percentage: 72,
    energy_density: 120,
    is_vegetarian: true,
    is_vegan: true,
    slider_min: 50,
    slider_max: 250,
  },

  // Vegetables
  {
    name: "Broccoli, Steamed",
    category: "vegetables",
    texture: "firm_solid",
    calories: 34,
    protein: 2.8,
    carbs: 7,
    fat: 0.4,
    fiber: 2.6,
    water_percentage: 89,
    energy_density: 34,
    is_vegetarian: true,
    is_vegan: true,
    slider_min: 50,
    slider_max: 300,
  },
  {
    name: "Spinach, Raw",
    category: "vegetables",
    texture: "soft_solid",
    calories: 23,
    protein: 2.9,
    carbs: 3.6,
    fat: 0.4,
    fiber: 2.2,
    water_percentage: 91,
    energy_density: 23,
    is_vegetarian: true,
    is_vegan: true,
    slider_min: 50,
    slider_max: 200,
  },
  {
    name: "Bell Pepper",
    category: "vegetables",
    texture: "firm_solid",
    calories: 31,
    protein: 1,
    carbs: 6,
    fat: 0.3,
    fiber: 2.1,
    water_percentage: 92,
    energy_density: 31,
    is_vegetarian: true,
    is_vegan: true,
    slider_min: 50,
    slider_max: 250,
  },
  {
    name: "Carrots",
    category: "vegetables",
    texture: "firm_solid",
    calories: 41,
    protein: 0.9,
    carbs: 10,
    fat: 0.2,
    fiber: 2.8,
    water_percentage: 88,
    energy_density: 41,
    is_vegetarian: true,
    is_vegan: true,
    slider_min: 50,
    slider_max: 200,
  },
  {
    name: "Tomatoes",
    category: "vegetables",
    texture: "soft_solid",
    calories: 18,
    protein: 0.9,
    carbs: 3.9,
    fat: 0.2,
    fiber: 1.2,
    water_percentage: 94,
    energy_density: 18,
    is_vegetarian: true,
    is_vegan: true,
    slider_min: 50,
    slider_max: 250,
  },

  // Fats and Oils
  {
    name: "Olive Oil",
    category: "fats_oils",
    texture: "liquid",
    calories: 884,
    protein: 0,
    carbs: 0,
    fat: 100,
    fiber: 0,
    water_percentage: 0,
    energy_density: 884,
    is_vegetarian: true,
    is_vegan: true,
    slider_min: 5,
    slider_max: 50,
  },
  {
    name: "Avocado",
    category: "fats_oils",
    texture: "soft_solid",
    calories: 160,
    protein: 2,
    carbs: 9,
    fat: 15,
    fiber: 7,
    water_percentage: 73,
    energy_density: 160,
    is_vegetarian: true,
    is_vegan: true,
    slider_min: 50,
    slider_max: 200,
  },

  // Nuts and Seeds
  {
    name: "Almonds",
    category: "nuts_seeds",
    texture: "firm_solid",
    calories: 579,
    protein: 21,
    carbs: 22,
    fat: 50,
    fiber: 12.5,
    water_percentage: 4,
    energy_density: 579,
    is_vegetarian: true,
    is_vegan: true,
    slider_min: 15,
    slider_max: 100,
  },
  {
    name: "Peanut Butter",
    category: "nuts_seeds",
    texture: "semi_liquid",
    calories: 588,
    protein: 25,
    carbs: 20,
    fat: 50,
    fiber: 6,
    water_percentage: 1,
    energy_density: 588,
    is_vegetarian: true,
    is_vegan: true,
    slider_min: 15,
    slider_max: 100,
  },
];

async function main() {
  console.log("Starting nutrition database seeding...");

  await db.transaction(async (tx) => {
    console.log("Seeding ingredients...");
    const insertedIngredients = await tx
      .insert(ingredients)
      .values(ingredientData)
      .returning();
    console.log(`Inserted ${insertedIngredients.length} ingredients`);
  });

  console.log("Nutrition database seeding completed successfully!");
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main();
}
